### ISSUE TITLE
PHP encoded binary fails utf-8 validators (mb_check and preg_match)

### ISSUE THREAD

**Issue by divinity76** [seizu/base128#1]
the binary data below after being base128 encoded fails mb_check_encoding validation and fails strict-mode mb_detect_encoding validation and fails preg_match validation, all 3 agree the output is not valid utf-8.  (but interestingly, it passes non-strict-mode mb_detect_encoding)

```php
<?php
$o=new base128();
$binary=hex2bin("73f3e10ff600d38549df"); // CS random bytes.
$enc=$o->encode($binary);

$res=[
    "enc"=>$enc,
    "mb_check_encoding pass"=>mb_check_encoding($enc,'UTF-8'),
    "mb_detect_encoding non-strict pass"=>mb_detect_encoding($enc,"UTF-8",false)==="UTF-8",
    "mb_detect_encoding strict pass"=>mb_detect_encoding($enc,"UTF-8",true)==="UTF-8",
    "preg_match //u pass"=>(bool)preg_match('//u', $enc)
];
var_dump($res);

```

actual output:

```php
array(5) {
  ["enc"]=>
  string(12) "ª,§Hl�):�*"
  ["mb_check_encoding pass"]=>
  bool(false)
  ["mb_detect_encoding non-strict pass"]=>
  bool(true)
  ["mb_detect_encoding strict pass"]=>
  bool(false)
  ["preg_match //u pass"]=>
  bool(false)
}
```

expected output: 

```php
array(5) {
  ["enc"]=>
  string(12) "??something here??"
  ["mb_check_encoding pass"]=>
  bool(true)
  ["mb_detect_encoding non-strict pass"]=>
  bool(true)
  ["mb_detect_encoding strict pass"]=>
  bool(true)
  ["preg_match //u pass"]=>
  bool(true)
}
```

**Comment by seizu** [comment]
UTF8 is not used. Encoder and decoder is based on ISO-8859-1 only.

**Comment by divinity76** [comment]
@seizu if base128 is, and i quote, `Designed for web based applications` , shouldn't it use UTF-8? quoting [UTF-8's wikipedia page](https://en.wikipedia.org/wiki/UTF-8):

UTF-8 is the dominant encoding for the [World Wide Web](https://en.wikipedia.org/wiki/World_Wide_Web) (and internet technologies), accounting for 97.8% of all web pages, and up to 100.0% for many languages, as of 2023.[[7]](https://en.wikipedia.org/wiki/UTF-8#cite_note-W3TechsWebEncoding-8) Virtually all countries and languages have 95.0% or more use of UTF-8 encodings on the web.

**Comment by seizu** [comment]
I don't know your use case, but if you want to store or display binary data as **text**, while remaining UTF8 compliant, I would recommend base64_encode. The filesize will of course be larger then.
